topicName: "applesauce"
encryptionKey: "$QjsDHE5Hge*tAd-zLQwJbW2mFu5GsCh"
logLevel: "ERROR"
listenAddress: "/ip4/0.0.0.0/tcp/0"
maxMessageSize: 10485760
retryInterval: 2000 
logFile: "app.log"
mdns:
  enabled: true
  serviceTag: "my-mdns-service"
useSSL: false  
torNodes: 3
zkpDifficulty: 10
dhtBootstrap: "/ip4/0.0.0.0/tcp/0"