FROM golang:1.22-alpine

WORKDIR /app

# Instalar dependencias del sistema
RUN apk add --no-cache git gcc musl-dev

# Copiar solo los archivos necesarios
COPY go.mod go.sum ./
COPY *.go ./
COPY config-node1.yaml ./config.yaml

# Descargar dependencias
RUN go mod download

# Compilar la aplicación
RUN go build -o p2p-app main.go flood_protection.go

# Exponer puertos
EXPOSE 8080
EXPOSE 4001

# Comando para ejecutar la aplicación
CMD ["/app/p2p-app"]
